### ISSUE TITLE
Problemchen im Chrome Dev-Tools Tablet Modus

### ISSUE THREAD

**Issue by wolfspelz** [lupuslabs/n3qExt#104]
- Avatare stehen ganz unten auf Seite (nicht untem am sichtbaren Bereich, sondern body-bottom)
- Backpack Fenster auch nicht sichtbar (auch von body-bottom positioniert?)
- move Backpack window per touch/swipe an Title-Bar resized Window statt move

(git pull develop heute (Fr.) morgen)

**Comment by AllanWegan** [comment]
Touch-Drag war ultra finnicky weil tablet mode eher fuzzy ist und nicht die abmessungen von Elementen respektiert - gefixt indem wieder die Title-Bar das Drag-handling macht, wenn das Fenster eine solche hat (commit 438322236d89d5a1433520486e37a1dfd2157d40).

Auf welcher Site tritt der Positionierungsfehler auf?

**Comment by wolfspelz** [comment]
> Auf welcher Site tritt der Positionierungsfehler auf?

https://www.galactic-developments.de/

Mit freundlichem Gruß
hw
--
Dr. Heiner Wolf
Autor, Dev, Agile Coach, CTO

**Comment by AllanWegan** [comment]
Da ist ein DIV in nem A auf der Seite. Das triggert so ne Art Quirks-Mode und der ignoriert im Tablet-Mode "position: fixed".
Selector: html > body > #page > #bgtop > #closebutton > a > div

Won't fix.
