### ISSUE TITLE
Auf google.com gegangen: bin ausgegraut. Item auf Seite gestellt: Item nicht sichtbar. Ralf sieht mich nicht. Musste Extension neu landen um das zu beheben.

### ISSUE THREAD

**Issue by wolfspelz** [lupuslabs/n3qExt#105]
![Image](https://user-images.githubusercontent.com/2523531/218670528-f7fbdb6c-4cd0-4e1a-8d87-756a784105fa.png)

**Comment by AllanWegan** [comment]
Maybe fixed in c03dcf7fa916f43f0e7b31196c982f73f46fa9b5.
