### ISSUE TITLE
Bei Ralf: während mein Paintball läut ist bei ihm auf Google die Seite weiß

### ISSUE THREAD

**Issue by wolfspelz** [lupuslabs/n3qExt#106]
Ralf sagte gestern auch: wenn ich die bälle werfe wird die Seite weiss, danach wieder normal

![Image](https://user-images.githubusercontent.com/2523531/218670784-a824c97e-279d-412f-bc06-73f284ac978d.png)

**Comment by AllanWegan** [comment]
Done in 29c8af4c964217765952a09ad485bb09f001439b.
