### ISSUE TITLE
Mouseown-Mousemove verschiebt das Fenster -> kein Text Select

### ISSUE THREAD

**Issue by wolfspelz** [lupuslabs/n3qExt#112]
Text selektieren und copy wäre schön. 
- verschieben ist nett, aber copy/paste wäre mir wichtiger
- wenn verschieben, dann mit Titelleiste (oder zumindst nur "oben", z.B. zwischen edge und titel) 
- oder gar kein Verschieben, dafür Text selektieren. 
- BadgeInfoWindow
- BackpackItemInfo
- Toast
- Nickname (kein select aber verschiebt nicht)

**Comment by AllanWegan** [comment]
Done in 5286fe880eba75c9a2214dfcec12151a2c4b2296, 90a59281b69329719367e7cdffdad18a42e30185 (badge info), bb61cbc28b076e103aac37962511cec3983006e2 (nicknames).
