### ISSUE TITLE
Error when trying to drag an item info box

### ISSUE THREAD

**Issue by AllanWegan** [lupuslabs/n3qExt#12]
Steps to reproduce:
- Open backpack.
- Click on any item to bring up its info box.
- Position the mouse pointer inside the info box.
- Try to drag the info box or a button by moving the mouse pointer outside the box while holding the left mouse button pressed.
- A JavaScript error is triggered inside jQuery-UI's scroll-parent.js.

Ideas of how to fix it:
- Update jQuery/jQuery-UI to newest stable as it might have been fixed there.
- Find out, what seperates the info boxes from other GUI elements as the error doesn't seem to happen anywhere else.

**Comment by wolfspelz** [comment]
Still? after making the BackpackIteminfo toplevel and selectable

**Comment by AllanWegan** [comment]
Fixed by removing JQuery event handling in 20eec8aae33b482788a95230f54c981151ca6704.
