### ISSUE TITLE
RoomItemHover bleibt stehen

### ISSUE THREAD

**Issue by wolfspelz** [lupuslabs/n3qExt#121]
- beim Mining
- Dirt/Sand umsortieren in der normalen dig-wait-heap-wait-dig Abfolge
- irgendwann wohl während dem Stacking ein Hover ausgelöst
- Vielleicht wurde beim Item Stacking das Item gelöscht während das Hover da war
- oder: keep-alive presence während Hover?
- oder: "dig" gedrückt zu schnell nach Hover?
- jedenfalls gibt es einen Mechanismus, der das Hover links am Rand persistiert
- Das Hover ist links am Rand
- Es geht nicht mehr weg 
- 2 mal passiert bei 40 dig-stack Runden
- vielleicht musst du mal viel minen und stacken um das zu reproduzieren

![Image](https://user-images.githubusercontent.com/2523531/222378504-8d00e88f-041e-4926-8b2a-8da44b245eaa.png)

**Comment by AllanWegan** [comment]
Fixed the race in 11d5f293c46b18d3a17b3311e036afbb3121a614.
