### ISSUE TITLE
NFT Fahne benhauptet auf allen Webseiten, dass sie "dir gehört". Sollte das nur auf den richtigen  anzeigen.

### ISSUE THREAD

**Issue by wolfspelz** [lupuslabs/n3qExt#143]

**Comment by AllanWegan** [comment]
Obtaining a debug item the normal way failed because MetadataController relies on a magic inventory which never got populated on my dev system.
Will try again once i had the chance to secretly obtain the attributes of Heiner's cheat flag on galactic developments...

**Comment by AllanWegan** [comment]
Not a bug.

Any ClaimAspect with a ClaimUrl has strength zero on all pages not mapping to the same room as defined in ClaimUrl.
So any ClaimAspect item with a strength greater zero (including the default pirate flag) kicks it from the page.
But as long as no one contests a claim, claim strength doesn't matter and a claim is a claim.

I verified that kicking by standard pirate flag works as intended on pages not mapping to same room as ClaimUrl and doesn't work on the page mentioned in ClaimUrl.

**Comment by wolfspelz** [comment]
ok, fair enough
