### ISSUE TITLE
Users can't see avatars outside their browser window on Firefox

### ISSUE THREAD

**Issue by AllanWegan** [lupuslabs/n3qExt#151]
Zooming the page in Firefox only affects font sizes. Avatar size and positioning is not affected.
When a user switches to a lower resolution screen, he can get stranded without access to his avatar and menu.
Other user's avatars positioned further right than screen width are completely out of reach too.

**Comment by wolfspelz** [comment]
Sicher dass das keine lokale Einstellung ist?
Bei mir genauso wie bei Chrome.
![Unbenannt](https://github.com/lupuslabs/n3qExt/assets/2523531/3f7558b8-64cc-4466-921f-0dba72c341ff)

**Comment by AllanWegan** [comment]
War ein User-Error. Hatte wohl schonmal irgendwann Firefox aufm Main und damals auf Textzoom umgestellt. Default ist voller Zoom.
