### ISSUE TITLE
Not usable on tablets due to missing swipe support. 

### ISSUE THREAD

**Issue by wolfspelz** [lupuslabs/n3qExt#23]
No swipe events supported
Maybe: https://www.npmjs.com/package/jquery-ui-touch-punch

Tasks:
- [x] Make windows touch-compatible (done in 45c301c18c1469afdb7959a840b6ed7c5b75c7b9)
- [x] Fully remove jquery-ui dependency (done in 45c301c18c1469afdb7959a840b6ed7c5b75c7b9)
- [x] Hunt down and convert remaining uses of JQuery for pointer-related event handling /done in 20eec8aae33b482788a95230f54c981151ca6704)
- [x] #48
- [x] Tablet: Fix Doubleclick detection (actually was pointer IDs changing for each initial pointerdown in Chrome, done in cd36ff8bd6a67ab4e709a88c52e64a11d3439792)
- [x] Tablet: long press statt hover (done in ee9ed65244253df0060d80f1c39ace8c05e0f8d0)

**Comment by AllanWegan** [comment]
Still missing the JQuery update for window move/resize and #48 unfixed for touch/pen input.
