### ISSUE TITLE
Emote/animations menu is static. Does not adapt to available animations

### ISSUE THREAD

**Issue by wolfspelz** [lupuslabs/n3qExt#33]
The menu is currently driven by CSS. It should open close by code. Then menu items can be created as the menu opens rather than creating the menu with the avatar once. Not to speak of sparing the DOM many unused/hudden menu items.

See also #15

**Comment by AllanWegan** [comment]
Fixed in bef19e07fad5dd1645c4c30fac254fb954ead237.
