### ISSUE TITLE
Wrong open in new tab behavior in tour popup window

### ISSUE THREAD

**Issue by AllanWegan** [lupuslabs/n3qExt#5]
Current behavior: When doing the tour and on any site CTRL-clicking on any link inside the tour guide popup window, the browser opens the tour guide window in a new tab and navigates to the target side in the current tab.

Expected behavior: When doing the tour and on any site CTRL-clicking on any link inside the tour guide popup window, the browser opens the clicked link in a new tab and does not navigate in the current tab.

Tested on Chrome on Windows 10 x64.

**Comment by wolfspelz** [comment]
wont fix
