### ISSUE TITLE
Sprechblase sollte auch bei großen Avataren über dem Kopf sein. Sprechblasenkoordinate in Avatarconfig?

### ISSUE THREAD

**Issue by wolfspelz** [lupuslabs/n3qExt#59]
chat bubble coordinate (bubblebottom)
chat-in line coordinate (chatinbottom)
avatar shadow (als eigene story)

**Comment by AllanWegan** [comment]
`<param name='speechBubbleOffsetBottom' value='110'/>` as default for old avatars and value something around 170 for RPM avatars?

**Comment by AllanWegan** [comment]
Done in 95315f6747f2a39d2eb355a98e77f35b1c8ed2ba and 1a766b4cb24993e8d67be144b2ebe23ca2e0b706.
Use demonstrated in [nine3q 4336593f34932cd72876cbb77eec3d18838d004f](https://github.com/lupuslabs/nine3q/commit/02d8dad422c783a834a7f6701294424ebe1a6ee9).
Configurable shadow task extracted into #73.
