### ISSUE TITLE
Backpack windwos resize verliert Fokus wenn Maus über BackpackItem UND über Avatar

### ISSUE THREAD

**Issue by wolfspelz** [lupuslabs/n3qExt#63]

**Comment by AllanWegan** [comment]
Done in ac3a58f9016fb3ea3062d77deb1e379176dca5ef.

**Comment by wolfspelz** [comment]
Super, geht

Mit freundlichem Gruß
hw
--
Dr. Heiner Wolf
Autor, Dev, Agile Coach, CTO
