### ISSUE TITLE
Aktionen-Menu verstecken unter einem "Aktionen"-Menupunkt. Nur eine Spalte, damit Menu bei ersten Eindruck kleiner ist. 

### ISSUE THREAD

**Issue by wolfspelz** [lupuslabs/n3qExt#67]
Delay Untermenu zumachen (0,5sec?), wenn kein anders aufgeht.

- Klar, dafür muss man das Aktionen-Submenu aufklappen (war im alten weblin auch so)
- Aktionen-Menupunkt mit Icon und Pfeil
- Aktionen-Submenu aufklappen bei Klick oder nach kurzer Verzögerung (wie alle typischen Windows-Menus)
- Dann hat das Menu nur noch eine Spalte
- Ganzes Menu umbauen von CSS-gesteuert auf prozedural generiert beim Klick auf Burger-Button
- Kein Animationseffekt (außer wenn er billig ist)

**Comment by AllanWegan** [comment]
Done in bef19e07fad5dd1645c4c30fac254fb954ead237.

**Comment by AllanWegan** [comment]
Submenu close delay done in 768671a03ec22db289fb3b26378f83c76ba74a7e.
