### ISSUE TITLE
Menu-Button verschwindet während Menü offen ist.

### ISSUE THREAD

**Issue by wolfspelz** [lupuslabs/n3qExt#71]
![Untitled](https://user-images.githubusercontent.com/2523531/203924847-c9fbba7e-ef97-4385-990e-bcf1ed8f8eed.png)
Bei anderen Avataren (nicht "self") kommt der Name bei hover. Wenn man Menü aufklickt, kommt Menü. Aber wenn man über das Menü geht, verschwindet der Name mit Name mit Menü-Button. Name mit Menü-Button sollte bleiben solange Menü offen ist.

UND:

Wenn Menü offen, Maus raus, dann weg-fade. Maus wieder rein und hover, dann kommt geöffnetes Menü wieder. Sollte dann zu sein?

**Comment by AllanWegan** [comment]
Fixed in 38e2035fee7564e479d4d5f55e0b4cca9def6a7a.
