### ISSUE TITLE
RPM Avatare

### ISSUE THREAD

**Issue by wolfspelz** [lupuslabs/n3qExt#72]
- Marvin macht 2 x 10 normale (m/w) Avatare und 20-30 mit fancy Aussehen
- Marvin übergibt uns die Avatar-Items
- Avatardaten runterladen, damit sie im Filesystem sind wie die anderen Standardavatare, damit die Struktur kompatibler ist zu den alten. Mapping is bisher AvatarId -> webex-URLs, möchte nicht ein neues Mapping machen müssen mit ItemId -> Blobstorage-URLs, Basisdienst soll ohne Items gehen, also FiIes auf webex.
- Speichern unter avatars/rpm1/*
- In Ext-Config die neuen vor den alten einsortieren, alle alten behalten, die alten normalen ganz hinten
- Zufallsavatar beim Start aus den neuen wählen (sollte dann nur noch eine Config-Änderung sein)
- Anpassung nötig in Ext damit nicht-GIF Avatare als Standardavatare gehen? Bisher wird aus AvatarId der Pfad .../avatars/gif/$AvatarId (AvatarId=rpm/1/070I8pPQp7 usw.)
- `            list: {
                'rpm/1/070I8pPQp7': { 'preview': 'idle.webp' },
                'rpm/2/DEKQjbtXvi': { 'preview': 'idle.webp' },
                'gif/002/sportive03_m': { 'preview': 'idle.gif' },
            },
`
- Klären wir bei 100x100 px in den Settings bleiben. Oder 200x200 und die alten sind 100x100 mittig im 200x200 Quadrat
- Nein, ich glaube nicht, das wir dabei die Avatarauswahl in den Settings umbauen, machen wir später.
- Avatargenerator Avatare: "RPM Avatar" -> "Avatar"

Vorschlag:
![gallery1](https://user-images.githubusercontent.com/2523531/204607868-4faa13da-20d2-4ad2-b812-b757a759b2f9.png)

![gallery2](https://user-images.githubusercontent.com/2523531/204607883-76fd04da-b7db-4ba5-942b-be942446c1a4.png)

**Comment by AllanWegan** [comment]
Support implementiert in Client und Server. Weiter gehts, wenn die Avatare fertig sind.

**Comment by wolfspelz** [comment]
Ralf (für nicht normal Palette):
https://nine3qstorage.blob.core.windows.net/n3qdata/avatar/2022/12/02/14/070I8pPQp7/config.xml
https://nine3qstorage.blob.core.windows.net/n3qdata/avatar/2022/12/02/09/kmolr4gUWF/config.xml
https://nine3qstorage.blob.core.windows.net/n3qdata/avatar/2022/12/02/10/8EcmgjttLF/config.xml
https://nine3qstorage.blob.core.windows.net/n3qdata/avatar/2022/12/02/10/80fUee3j1i/config.xml
https://nine3qstorage.blob.core.windows.net/n3qdata/avatar/2022/08/08/08/1b6wOjW4kw/config.xml
https://nine3qstorage.blob.core.windows.net/n3qdata/avatar/2022/12/02/09/DEKQjbtXvi/config.xml
https://nine3qstorage.blob.core.windows.net/n3qdata/avatar/2022/12/02/10/IEHxuTiipC/config.xml
https://nine3qstorage.blob.core.windows.net/n3qdata/avatar/2022/12/02/10/E6jeOijSlL/config.xml
https://nine3qstorage.blob.core.windows.net/n3qdata/avatar/2022/12/02/10/NFHc5n21M5/config.xml

**Comment by AllanWegan** [comment]
Im Prinzip so nutzbar und schon einigermaßen divers. Aber ich geh die noch mal durch und mach noch ein par Avatare für unterrepräsentierte Gruppen und Archetypen.

**Comment by AllanWegan** [comment]
Done. Galleries configured server side. Gallery 1 in client config as fallback.

**Comment by wolfspelz** [comment]
randomAvatarIds: sollten nur "normale" enthalten keine "fancy" damit man beim Start was normales bekommt

**Comment by AllanWegan** [comment]
Es sind nur "normale" in der Random-Liste. Welche Avatare sollen in fancy verschoben werden?

**Comment by wolfspelz** [comment]
Habe nur die Anzahl bewundert und daraus geschlossen, dass normal und fancy vermischt sind. Wusste nicht dass es so viele normale gibt

**Comment by AllanWegan** [comment]
Okilidokili.

Vergiss nicht, dass wir neuerdings immer ne index.html in die Gallerieordner legen.
Da kannste auch mit Linksklick in die rechte obere Ecke das "Debug"-Menu sichtbar machen, dann mit Shift+Linksklick Avatare selektieren und deren IDs/Namen dann aus dem Textfeld rauskopieren - falls du doch welche umziehen willst und wissen willst, wie die heißen.
