### ISSUE TITLE
Besprechen: Ergebnis fürs Iframe-Durchklicken-Testen:

### ISSUE THREAD

**Issue by wolfspelz** [lupuslabs/n3qExt#74]
- Iframes sehen intern keine Events wenn das Iframe-Element 'pointer-events: none;' hat.
- Events werden innerhalb des Iframe-Dokuments geschluckt, wenn das Iframe-Element 'pointer-events: auto;' hat.
- Prinzipiell kann man Pointer-Events faken. Im Iframe kann man also die Events auf dem HTML-Element auffangen und dann im Parent-Dokument schauen, welches Element da drunter liegt und die neu werfen. Das geht vermutlich unabhängig von Security-Kram, weil wir dem Event-handler im Iframe einfach ne Referenz aufs Parent-Dokument-DOM geben können (wir machen den ja im Contentscript und das hat Zugriff auf alles). Gefälsche Events sind aber als nicht-vom-Nutzer initiiert markiert und triggern keine Default-Aktionen (was ja eigendlich der Sinn der ganzen Sache wäre).

Fazit: Iframe für die ganze GUI fällt flach. Durch Avatar-Iframes könnte man nicht auf Seiteninhalte durchklicken (unseren eigenen Kram bekommen wir kompatibel).

Shadow-DOM-Test-Box implementiert.

**Comment by wolfspelz** [comment]
Auf www.galactic-developments.de ist "Script" schwarz

**Comment by AllanWegan** [comment]
Nur das linke - click drauf und es wird grün.
