### ISSUE TITLE
gedraggedte Items bleiben als Shadow stehen

### ISSUE THREAD

**Issue by wolfspelz** [lupuslabs/n3qExt#76]
Ralf und ich haben RPM Avatare getasch. Bei mir und bei ihm blieb was stehen:

![Untitled](https://user-images.githubusercontent.com/2523531/206007566-2ea5f3d4-1b59-46e9-bc49-8aae780f63f4.png)

**Comment by AllanWegan** [comment]
Fixed in a10d75f8dd98a3e92b204a458431fb8b587e4000.
