### ISSUE TITLE
Images for Backpack items are blocked by CSP

### ISSUE THREAD

**Issue by AllanWegan** [lupuslabs/n3qExt#8]
The image downloads are affected by CSP image source domain restrictions (and 3rd-party content blockers like uMatrix) while images of avatars and rezzed items (loaded by the background page) are working fine.

Proposed solution: Request backpack item images in background page context too.

**Comment by wolfspelz** [comment]
Wierd thing: only sometimes. Sometimes only one is missing.

**Comment by AllanWegan** [comment]
Done in fcf1078945412555e324d54f7990c6ae0a749a3b.

**Comment by AllanWegan** [comment]
Data-URLs specified in inline-styles ("background-image: url(data:<imageBase64>);") are blocked by CSP at https://developer.mozilla.org/. IMG tag src-attributes still work fine there.
