### ISSUE TITLE
Display minimieren, damit weniger stört, wenn man die Webseite bedienen will (z.B. Buttons am unteren Rand).

### ISSUE THREAD

**Issue by AllanWegan** [lupuslabs/n3qExt#84]
- Farbe
![Untitled-1](https://user-images.githubusercontent.com/2523531/209407090-fac526d1-7776-4840-9570-bd7a9c8a9904.png) #888888
- Chat type damit filtern einfacher

- Extension Symbol verbirgt Display temporär (nicht merken, bei reload resettet), 
- User bleibt im room, 
- Hinweis auf chat/toast Aktivität im room auf dem Extension Icon (roter Punkt?). ODER als Symbol ("!"?) neben der Zahl im browser_action.badge
- Anzahl der anderen Avatare als Zahl
- Idle-mäßiger presence-state (halb durchsichtig)

**Comment by AllanWegan** [comment]
Done in b2cb7c58006f5ff906ec8e7ce1f78c570e8eb611.

**Comment by AllanWegan** [comment]
Weil der Browser die Schrift weiß färbt wenn die Badgefarbe zu dunkel ist und dann der Kontrast lausig ist, habe ich ein helleres Grau genommen (Farben sind in Config; Commit dd75c97122a7f695d6668420f695005c50f48eae).

Der ChatMessageType ist ohne Daten-Migration implementiert: Die History wird also einmalig beim Updaten auf den neuen Client gelöscht (Commit 2de832d5c66f7e341742f1be42f99ee2843ba966).

**Comment by wolfspelz** [comment]
interessant, OK.

Gruß
hw
--
Dr. Heiner Wolf
Autor, Dev, Agile Coach, CTO
