### ISSUE TITLE
Avatar-Menu moves with browser-top

### ISSUE THREAD

**Issue by wolfspelz** [lupuslabs/n3qExt#88]
- Menu aufmachen
- Browser-Fenster Höhe ändern
- voila

Man könnte Menu schließen, wenn sich Browser-größe ändert. Oder anders...

![tja](https://user-images.githubusercontent.com/2523531/209941876-bd077908-31c7-4c01-b21d-ad3555752147.png)

**Comment by AllanWegan** [comment]
Vermutlich positioniere ich das Menu per top. Wenn ich das auf bottom umstelle, müsste das das Problem  beheben ohne dass ich nen globalen Event-Handler setzen muss.

**Comment by wolfspelz** [comment]
auch gut

**Comment by wolfspelz** [comment]
ja das würde es fixen
