### ISSUE TITLE
Man kann auf Avataren und in der Nähe (vermutlich wo das Image ist) nicht rechts-Klicken

### ISSUE THREAD

**Issue by wolfspelz** [lupuslabs/n3qExt#89]
Rechtsklick -> Standard Menu

**Comment by AllanWegan** [comment]
Die Event-Transparenz für die transparenten Bereiche ist emuliert, indem Kopien der Events auf dem drunterliegenden Element neu getriggert werden. Das funktioniert für Linksklicks auf Links und vermutlich auch für Rechtsklicks auf Links die von Event-Handlern der Seite verarbeitet werden.
Aber die so generierten Events werden vom Browser nicht als direkt vom Nutzer generiert anerkannt und triggern daher keine Kontextmenüs oder Textselektion.

Vieleicht kann man da was mit CSS clip-path oder nem transparenten SVG (da funktioniert Event-Transparenz angeblich) machen. Aber dann müsste man die Avatare irgendwie als Pfad tracen, den man dann als interaktive Fläche verwendet. Das geht vermutlich performant genug wenn man das Ergebnis cached, erschien mir damals aber als zu viel Aufwand für den Nutzen...

**Comment by wolfspelz** [comment]
lass ma
