### ISSUE TITLE
WTF Feuerwerk

### ISSUE THREAD

**Issue by wolfspelz** [lupuslabs/n3qExt#90]
Nach dem Feuerwerk ist es eine Weile rumgestanden. Dann hat es plötzlich im Button angefangen "runmzumachen".

![Untitled](https://user-images.githubusercontent.com/2523531/210180631-e51f7f40-c3d8-48a7-9f36-c5064cfe078d.jpg)

**Comment by AllanWegan** [comment]
Passierte das nachdem ein selbstausgelöstes Feuerwerk geendet hat? Haben die das alle gleichzeitig gestartet?

**Comment by wolfspelz** [comment]
> Passierte das nachdem ein selbstausgelöstes Feuerwerk geendet hat? 

Ja

> Haben die das alle gleichzeitig gestartet?

Unbekannt. Habe es erst gesehen als alle liefen. Gefühlt haben alle gleichzeitig angefangen in den Moment als draußen ein Feuerwerk los ging.

**Comment by wolfspelz** [comment]
Not reproduced
